### ISSUE TITLE
TypeError: can't convert Symbol into Integer

### ISSUE THREAD

**Issue by henry74** [viralheat/sentiment_analysis#2]
I'm receiving the following error when attempting to run the following after creating a client with an API key:

ruby-1.9.2-p290 :004 > puts s.quota
5000
 => nil
ruby-1.9.2-p290 :005 > puts s.review("you are terrible")
TypeError: can't convert Symbol into Integer
        from /home/testuser/playground/sandbox/vendor/ruby/1.9.1/bundler/gems/sentiment_analysis-07df2537f6e8/lib/sentiment_analysis/client.rb:42:in `[]'
        from /home/testuser/playground/sandbox/vendor/ruby/1.9.1/bundler/gems/sentiment_analysis-07df2537f6e8/lib/sentiment_analysis/client.rb:42:in`review'
        from (irb):5
        from /home/testuser/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in `<main>'
ruby-1.9.2-p290 :006 > puts s.review("test")
TypeError: can't convert Symbol into Integer
        from /home/testuser/playground/sandbox/vendor/ruby/1.9.1/bundler/gems/sentiment_analysis-07df2537f6e8/lib/sentiment_analysis/client.rb:42:in`[]'
        from /home/testuser/playground/sandbox/vendor/ruby/1.9.1/bundler/gems/sentiment_analysis-07df2537f6e8/lib/sentiment_analysis/client.rb:42:in `review'
        from (irb):6
        from /home/testuser/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in`<main>'
ruby-1.9.2-p290 :007 >

**Comment by henry74** [comment]
Looks like it's an issue with the readme file not giving a correct example of calling the library.  It should actually read:

puts sa.review(:text => "i don't like this")
  # => {"prob":0.732603741199471,"mood":"negative","text":"i don't like this"}
